#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'teste'
        hostname: teste-desktop
        username: teste1
        password: 'jusbrasil!00'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - curl
        - netstat
        - git
        - wget
        - google-chrome-stable
    snaps:
        - name: spotify
          channel: stable
          classic: false
        - name: code
          channel: stable
          classic: false
        - name: slack
          channel: stable
          classic: false
        - name: notion-snap-reborn
          channel: stable 
          classic: false
        - name: dbeaver-ce
          channel: stable
          classic: false
        - name: postman 
          channel: stable
          classic: false
                
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    interactive-sections:
        - user-setup
        - keyboard-setup
        
